services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  WechatPayScoreBundle\Controller\:
    resource: '../../Controller/'
  WechatPayScoreBundle\Repository\:
    resource: '../../Repository/'
  WechatPayScoreBundle\Service\:
    resource: '../../Service/'
    public: true
  WechatPayScoreBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true

  WechatPayScoreBundle\EventSubscriber\ScoreOrderListener:
    arguments:
      $environment: '%kernel.environment%'
