services:
  _defaults:
    autowire: true
    autoconfigure: true

  # DataFixtures 服务（仅在 test 环境中加载）
  WechatPayScoreBundle\DataFixtures\:
    resource: '../../DataFixtures/*'
    tags:
      - { name: doctrine.fixture.orm, group: test }